$content = Get-Content -Raw -Path script.js
$content = $content -replace "let currentSearchQuery = '';", "let currentSearchQuery = '';`n        let currentTrackerStatus = 'watching';`n        let currentOpenedShow = null;"
$content = $content -replace "async function fetchShows\(networkId, btnElement, page = 1\) \{`r`n            if \(isLoading\) return;", "async function fetchShows(networkId, btnElement, page = 1) {`r`n            document.getElementById('tracker-sub-nav').style.display = 'none';`r`n            if (isLoading) return;"
$content = $content -replace "async function performSearch\(page = 1\) \{`r`n            if \(isLoading\) return;", "async function performSearch(page = 1) {`r`n            document.getElementById('tracker-sub-nav').style.display = 'none';`r`n            if (isLoading) return;"
$content = $content -replace "function showFavorites\(btnElement\) \{`r`n            currentMode = 'favorites';", "function showFavorites(btnElement) {`r`n            document.getElementById('tracker-sub-nav').style.display = 'none';`r`n            currentMode = 'favorites';"
$content = $content -replace "async function openModal\(show\) \{`r`n            document\.getElementById\('modal-title'\)\.innerText = show\.name;", "async function openModal(show) {`r`n            currentOpenedShow = show;`r`n            document.getElementById('modal-title').innerText = show.name;"
$content = $content -replace "let favorites = JSON\.parse\(localStorage\.getItem\('my_favorite_shows'\)\) \|\| \[\];`r`n            let favBtn = document\.getElementById\('favorite-btn'\);", "let watchedList = JSON.parse(localStorage.getItem('my_watched_shows')) || [];`r`n            let trackedShow = watchedList.find(s => s.id === show.id);`r`n            document.querySelectorAll('.status-btn').forEach(btn => btn.classList.remove('active'));`r`n            if (trackedShow && trackedShow.watch_status) {`r`n                const activeBtn = document.querySelector('.status-btn[data-status=""' + trackedShow.watch_status + '""]');`r`n                if (activeBtn) activeBtn.classList.add('active');`r`n            }`r`n`r`n            let favorites = JSON.parse(localStorage.getItem('my_favorite_shows')) || [];`r`n            let favBtn = document.getElementById('favorite-btn');"
$content = $content -replace "function exportData\(\) \{", "function setWatchStatus(status) {`r`n            if (!currentOpenedShow) return;`r`n            document.querySelectorAll('.status-btn').forEach(btn => btn.classList.remove('active'));`r`n            document.querySelector('.status-btn[data-status=""' + status + '""]').classList.add('active');`r`n`r`n            let watchedList = JSON.parse(localStorage.getItem('my_watched_shows')) || [];`r`n            let showIndex = watchedList.findIndex(s => s.id === currentOpenedShow.id);`r`n            `r`n            if (showIndex > -1) {`r`n                watchedList[showIndex].watch_status = status;`r`n            } else {`r`n                currentOpenedShow.watch_status = status;`r`n                watchedList.push(currentOpenedShow);`r`n            }`r`n            `r`n            localStorage.setItem('my_watched_shows', JSON.stringify(watchedList));`r`n            `r`n            if (currentMode === 'watched') {`r`n                const card = document.getElementById('card-' + currentOpenedShow.id);`r`n                if (card && currentTrackerStatus !== status) card.style.display = 'none';`r`n            }`r`n        }`r`n`r`n        function exportData() {"
Set-Content -Path script.js -Value $content -NoNewline
